global:
  environment: test

namespaces:
  application: sales-test-ns
  gateway: sales-gateway-ns

auth:
  replicaCount: 1
  image:
    repository: kubectlandchill/auth
    tag: test

customer:
  replicaCount: 1
  image:
    repository: kubectlandchill/customer
    tag: test

order:
  replicaCount: 1
  image:
    repository: kubectlandchill/order
    tag: test

invoice:
  replicaCount: 1
  image:
    repository: kubectlandchill/invoice
    tag: test

payment:
  replicaCount: 1
  image:
    repository: kubectlandchill/payment
    tag: test

salesUi:
  replicaCount: 1
  image:
    repository: kubectlandchill/sales-invoice-ui
    tag: test
  port: 3000

hpa:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"