apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.customer.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: customers
spec:
  replicas: {{ .Values.customer.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: customers-microservice
  template:
    metadata:
      labels:
        app: customers-microservice
    spec:
      containers:
        - name: customers-container
          image: {{ .Values.customer.image.repository }}:{{ .Values.customer.image.tag }}
          resources:
            limits:
              memory: {{ .Values.customer.resources.limits.memory }}
              cpu: {{ .Values.customer.resources.limits.cpu }}
            requests:
              memory: {{ .Values.customer.resources.requests.memory }}
              cpu: {{ .Values.customer.resources.requests.cpu }}
          ports:
            - containerPort: {{ .Values.customer.port }}
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: {{ .Values.configmaps.backend.name }}
          {{- if .Values.probes.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.customer.probePath }}
              port: {{ .Values.customer.port }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.customer.probePath }}
              port: {{ .Values.customer.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.customer.probePath }}
              port: {{ .Values.customer.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          {{- end }}