apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.invoice.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: invoice
spec:
  replicas: {{ .Values.invoice.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: invoice-microservice
  template:
    metadata:
      labels:
        app: invoice-microservice
    spec:
      containers:
      - name: invoice-container
        image: {{ .Values.invoice.image.repository }}:{{ .Values.invoice.image.tag }}
        ports:
        - containerPort: {{ .Values.invoice.port }}
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: {{ .Values.configmaps.backend.name }}
        resources:
          limits:
            memory: {{ .Values.invoice.resources.limits.memory }}
            cpu: {{ .Values.invoice.resources.limits.cpu }}
          requests:
            memory: {{ .Values.invoice.resources.requests.memory }}
            cpu: {{ .Values.invoice.resources.requests.cpu }}
          
        {{- if .Values.probes.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.invoice.probePath }}
            port: {{ .Values.invoice.port }}
          initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.startup.failureThreshold }}

        readinessProbe:
          httpGet:
            path: {{ .Values.invoice.probePath }}
            port: {{ .Values.invoice.port }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

        livenessProbe:
          httpGet:
            path: {{ .Values.invoice.probePath }}
            port: {{ .Values.invoice.port }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

        {{- end }}